/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    IconBtn: typeof import('./src/components/Button/IconBtn.vue')['default']
    MapContainer: typeof import('./src/components/MapContainer.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Titlebar: typeof import('./src/components/Titlebar.vue')['default']
  }
}
